config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :events
  resources :infos
  resources :videos
  resources :audios
  resources :photos
  resource :about
  resource :home
  resource :dashboard

  root 'homes#show'

end

app/models/video.rb
class Video < ActiveRecord::Base
  mount_uploader :album_art, AlbumArtUploader
  mount_uploader :audio_file, AudioUploader
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:album_art, :title, :description, :release_date, :artist_name, :video_file)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<section>
  <%= form_for @video, :html => {:multipart => true} do |f| %>
      <% if @video.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

            <ul>
              <% @video.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :album_art %><br>
        <p><%= image_tag(@video.album_art_url, width: 100, height: 100) if @video.album_art.present? %></p>
        <%= f.file_field :album_art %>
      </div>
      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_area :title %>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>
      <div class="field">
        <%= f.label :release_date %><br>
        <%= f.date_select :release_date %>
      </div>
      <div class="field">
        <%= f.label :artist_name %><br>
        <%= f.text_field :artist_name %>
      </div>
      <div class="field">
        <%= f.label :video_file %><br>
        <p>Please note that this is the last part of the youtube video link, after the "="</p>
        <%= f.text_field :video_file %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>
</section>

app/views/videos/edit.html.erb
<section class="views">
<h1 class="page-header">Edit video information</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path, class: "btn btn-default" %>
</section>

app/views/videos/index.html.erb
<section class="views">
  <h1 class="page-header">Maytronomy's Videos</h1>
  <div class="top">
    <ul class='maytroList'>
      <% @videos.each do |video| %>
          <li class='list-group-item'>
            <%= link_to(video) do %>
                <div class="maytroPicture">
                  <%= image_tag(video.album_art_url, width: 300) %>
                </div>
                <strong><%= video.title %></strong>
                <div class='maytroDesc'>
                  <p><%= truncate(video.description ,length: 35 )%><span class='readMore'> View »</span></p>
                </div>
                <% if current_user.try(:admin?) %>
                    <%= link_to 'Edit', edit_video_path(video), class: "btn btn-default" %>
                    <%= link_to 'Destroy', video, class: "btn btn-default", method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
            <% end %>
          </li>
      <% end %>
    </ul>
  </div>
  <br>
  <div class="btn btn-default">
    <i class="glyphicon glyphicon-new-window"></i>
    <%= link_to 'New Video', new_video_path %>
  </div>
</section>

app/views/videos/new.html.erb
<section class="views">
<h1 class="page-header">New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path, class: "btn btn-default" %>
</section>

app/views/videos/show.html.erb
<section class="views">
  <p id="notice"><%= notice %></p>
  <h1 class="page-header"><%= @video.title %></h1>
  <div class="pull-right">
    <p><strong>Released on: </strong><%= @video.release_date %></p>
    <h4>By : <%= @video.artist_name %></h4>
  </div>
  <div>
    <iframe width="700" height="500" src="http://www.youtube.com/embed/<%= @video.video_file %>" frameborder="0">
    </iframe>
  </div>
  <h3>
    <%= @video.description %>
  </h3>
  <% if current_user.try(:admin?) %>
      <%= link_to 'Edit Video Info', edit_video_path(@video), class: "btn btn-default" %>
      <%= link_to 'Delete Video', @video, class: "btn btn-default", method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
  <%= link_to 'Back', videos_path , class: "btn btn-default" %>
</section>