config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :events
  resources :infos
  resources :videos
  resources :audios
  resources :photos
  resource :about
  resource :home
  resource :dashboard

  root 'homes#show'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:picture, :description)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<section class="">
  <%= form_for @photo, :html => {:multipart => true} do |f| %>
      <% if @photo.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

            <ul>
              <% @photo.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field"><br>
        <%= f.label :picture %><br>
        <p><%= image_tag(@picture, width: 100, height: 100) if @picture.present? %></p>
        <%= f.file_field :picture %>
      </div><br>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div><br>
      <div class="actions">
        <%= f.submit %>
      </div></br>
  <% end %>
</section>

app/views/photos/edit.html.erb
<section class="views">
  <h1 class="page-header">Edit photo</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @photo, class: "btn btn-default" %>
  <%= link_to 'Back', photos_path, class: "btn btn-default" %>
</section>

app/views/photos/index.html.erb
<section class="text-center">
  <h1 class="page-header">Maytronomy's Galleria</h1>
  <div class="top">
    <ul class='maytroList'>
      <% @photos.each do |photo| %>
          <li class='list'>
            <%= link_to(photo) do %>
                <div class="maytroPicture">
                  <%= image_tag(photo.picture_url, :width => 300) %>
                </div>
                <div class='maytroDesc'>
                  <p><%= truncate(photo.description ,:length=>35 )%><span class='readMore'> View »</span></p>
                </div>
            <% end %>
          </li>
      <% end %>
    </ul>
  </div>
  <br>
  <div class="btn btn-info">
    <i class="glyphicon glyphicon-new-window"></i>
    <%= link_to 'New Photo', new_photo_path %>
  </div>
</section>

app/views/photos/new.html.erb
<section class="views">
  <h1 class="page-header">New photo</h1>

  <%= render 'form' %>

  <%= link_to 'Back', photos_path %>
</section>

app/views/photos/show.html.erb
<section class="text-center">
  <p id="notice"><%= notice %></p>
  <p>
    <%= image_tag(@photo.picture_url, width: 800, class: "show-image") if @photo.picture_url.present? %>
  </p><br>

  <h3 class="page-header">
    <%= @photo.description %><br>
  </h3>
  <%= link_to 'Edit', edit_photo_path(@photo) %> |
  <div class="btn btn-info">
    <i class="glyphicon glyphicon-chevron-left"></i>
    <%= link_to 'Back', photos_path %>
  </div>
</section>