config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :events
  resources :infos
  resources :videos
  resources :audios
  resources :photos
  resource :about
  resource :home
  resource :dashboard

  root 'homes#show'

end

app/models/info.rb
class Info < ActiveRecord::Base
  mount_uploader :pic_story, PicStoryUploader
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: [:show, :edit, :update, :destroy]

  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { render :show, status: :ok, location: @info }
      else
        format.html { render :edit }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url, notice: 'Info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:title, :story, :reporter, :pic_story)
    end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.erb
<%= form_for @info, :html => {:multipart => true} do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :story %><br>
    <%= f.text_area :story %>
  </div>
  <div class="field">
    <%= f.label :reporter %><br>
    <%= f.text_field :reporter %>
  </div>
  <div class="field">
    <%= f.label :pic_story %><br>
    <%= f.file_field :pic_story %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<h1>Listing infos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Story</th>
      <th>Reporter</th>
      <th>Pic story</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td><%= info.title %></td>
        <td><%= info.story %></td>
        <td><%= info.reporter %></td>
        <td><%= info.pic_story %></td>
        <td><%= link_to 'Show', info %></td>
        <td><%= link_to 'Edit', edit_info_path(info) %></td>
        <td><%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Info', new_info_path %>

app/views/infos/new.html.erb
<h1>New info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @info.title %>
</p>

<p>
  <strong>Story:</strong>
  <%= @info.story %>
</p>

<p>
  <strong>Reporter:</strong>
  <%= @info.reporter %>
</p>

<p>
  <strong>Pic story:</strong>
  <%= @info.pic_story %>
  <%= image_tag(@info.pic_story_url, :width => 600) if @info.pic_story.present? %>
</p>

<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>