config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :events
  resources :infos
  resources :videos
  resources :audios
  resources :photos
  resource :about
  resource :home
  resource :dashboard

  root 'homes#show'

end

app/models/audio.rb
class Audio < ActiveRecord::Base
  mount_uploader :album_art, AlbumArtUploader
  mount_uploader :audio_file, AudioUploader
end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/info.rb
class Info < ActiveRecord::Base
  mount_uploader :pic_story, PicStoryUploader
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
  mount_uploader :album_art, AlbumArtUploader
  mount_uploader :audio_file, AudioUploader
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def show
  end
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  before_action :set_audio, only: [:show, :edit, :update, :destroy]

  # GET /audios
  # GET /audios.json
  def index
    @audios = Audio.all
  end

  # GET /audios/1
  # GET /audios/1.json
  def show
  end

  # GET /audios/new
  def new
    @audio = Audio.new
  end

  # GET /audios/1/edit
  def edit
  end

  # POST /audios
  # POST /audios.json
  def create
    @audio = Audio.new(audio_params)

    respond_to do |format|
      if @audio.save
        format.html { redirect_to @audio, notice: 'Audio was successfully created.' }
        format.json { render :show, status: :created, location: @audio }
      else
        format.html { render :new }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /audios/1
  # PATCH/PUT /audios/1.json
  def update
    respond_to do |format|
      if @audio.update(audio_params)
        format.html { redirect_to @audio, notice: 'Audio was successfully updated.' }
        format.json { render :show, status: :ok, location: @audio }
      else
        format.html { render :edit }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audios/1
  # DELETE /audios/1.json
  def destroy
    @audio.destroy
    respond_to do |format|
      format.html { redirect_to audios_url, notice: 'Audio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audio
      @audio = Audio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audio_params
      params.require(:audio).permit(:album_art, :title, :description, :release_date, :artist_name, :audio_file)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :picture, :description, :venue, :date)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: [:show, :edit, :update, :destroy]

  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { render :show, status: :ok, location: @info }
      else
        format.html { render :edit }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url, notice: 'Info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:title, :story, :reporter, :pic_story)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maytro</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href='http://fonts.googleapis.com/css?family=Cinzel:400,700|Lobster' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navigate">
  <div class="container-fluid">
    <h1><%= link_to 'MAYTRONOMY', root_path, class: 'navbar-brand' %></h1>
    <ul class="navbar-text pull-right">
      <li class="navbar-link"><span class="glyphicon glyphicon-headphones"></span><%= link_to 'SONGS', audios_path %></li>
      <li class="navbar-link"><span class="glyphicon glyphicon-facetime-video"></span><%= link_to 'VIDEOS', videos_path %></li>
      <li class="navbar-link"><span class="glyphicon glyphicon-camera"></span><%= link_to 'GALLERIA', photos_path %></li>
      <li class="navbar-link"><span class="glyphicon glyphicon-calendar"></span><%= link_to 'EVENTS', events_path %></li>
    </ul>
  </div>
</nav>
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>
<section class="container-fluid">
  <%= yield %>
</section>
<footer class="text-center">
  <ul>
    <li><span class="glyphicon glyphicon-headphones"></span><%= link_to 'SONGS', audios_path, class: '' %></li>
    <li><span class="glyphicon glyphicon-facetime-video"></span><%= link_to 'VIDEOS', videos_path, class: '' %></li>
    <li><span class="glyphicon glyphicon-camera"></span><%= link_to 'GALLERIA', photos_path, class: '' %></li>
    <li><span class="glyphicon glyphicon-calendar"></span><%= link_to 'EVENTS', events_path, class: '' %></li>
  </ul>
  <a href="/">© 2015 Maytronomy Music</a><br>
  Design By: <a href="#">Monsieur Slim</a>
  <div class="admin">
    <% if user_signed_in? %>
        <%= link_to 'Edit profile', edit_user_registration_path, class: 'btn btn-default' %>
        <%= link_to 'Dashboard', dashboard_path, class: 'btn btn-default' %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-default'  %>
    <% else %>
        <%= link_to "Login", new_user_session_path, class: 'btn btn-default'  %>
    <% end %>
  </div>
</footer>
</body>
</html>